<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
def matrix_mul(A, B):
    num_rows_A = len(A)
    num_columns_A = len(A[0])
    num_rows_B = len(B)
    num_columns_B = len(B[0])

    # To multiply an m×n matrix by an n×p matrix, the ns must be the same,
    # and the result is an m×p matrix.
    if num_columns_A != num_rows_B:
        print("Matrix multiplication of two arguments not possible as number of columns in first Matrix is NOT equal to the number of rows in second Matrix")
        return

    # Create an result matrix which will have
    # dimensions of num_rows_A x num_columns_B
    # And fill this matrix with zeros
    result_matrix = [[0 for i in range(num_columns_B)] for j in range(num_rows_A)]

    # Now implementing the key principle
    # The element at row i, column j is the product of the ith row of matrix A and the jth column of matrix B.

    for i in range(num_rows_A):
        for j in range(num_columns_B):
            for k in range(num_columns_A):
                # k-th column of A should be the k-th row of B
                result_matrix[i][j] += A[i][k] * B[k][j]
    return result_matrix


A = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6]]

B = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]

A1 = [[1, 2],
      [3, 4]]

B1 = [[1, 2, 3, 4, 5],
      [5, 6, 7, 8, 9]]


A2 = [[1, 3, 4], [5, 9, 6]]

B2 = [[1, 0, 0], [0, 0, 1]]

print(matrix_mul(A, B))
print(matrix_mul(A1, B1))
print(matrix_mul(A2, B2))


[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]
Matrix multiplication of two arguments not possible as number of columns in first Matrix is NOT equal to the number of rows in second Matrix
None


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
#Referance-https://stackoverflow.com/questions/57892112/select-a-number-randomly-with-probability-proportional-to-its-magnitude-from-the
import random


lst=[0, 5 ,27, 6, 13, 28, 100, 45, 10,79]   

def pick_a_number_from_list(A):
    weights1=[]
    
    for i in A:
        weights1.append(i/sum(lst))
        
    selected_random_number = random.choices(A,weights=weights1,k=1)    
    
    return selected_random_number


def sampling_based_on_magnitued():
    for i in range(1,100):
        number=pick_a_number_from_list(lst)
        print(number)
    

sampling_based_on_magnitued()


[79]
[28]
[100]
[100]
[79]
[28]
[100]
[28]
[5]
[27]
[79]
[100]
[100]
[10]
[100]
[45]
[79]
[79]
[100]
[27]
[45]
[79]
[45]
[28]
[79]
[100]
[100]
[79]
[45]
[27]
[100]
[5]
[45]
[5]
[100]
[13]
[28]
[100]
[27]
[100]
[13]
[28]
[45]
[100]
[100]
[79]
[100]
[45]
[27]
[10]
[27]
[100]
[10]
[45]
[79]
[100]
[79]
[100]
[100]
[100]
[5]
[79]
[45]
[10]
[100]
[100]
[100]
[27]
[79]
[79]
[10]
[100]
[79]
[79]
[45]
[100]
[79]
[10]
[100]
[45]
[28]
[79]
[45]
[100]
[28]
[45]
[100]
[79]
[45]
[100]
[100]
[79]
[45]
[100]
[45]
[100]
[45]
[79]
[45]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
#reference -https://stackoverflow.com/questions/57007469/is-there-a-regex-to-replace-the-digits-in-the-string-with-and-remove-all-the
import re

examples = ['234',
'a2b3c4',
'abc',
'#2a$#b%c%561#']

for example in examples:
    new_s = '#' * len(re.sub(r'\D', '', example))
    print('Input = {} Output = {}'.format(example, new_s))


Input = 234 Output = ###
Input = a2b3c4 Output = ###
Input = abc Output = 
Input = #2a$#b%c%561# Output = ####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
import math


def display_dash_board(marks, students):

    # zip() method - will bind together corresponding elements of students and marks
    marks_to_students_zipped = list(zip(marks, students))

    # print(marks_to_students_zipped)
    # [(45, 'student1'), (78, 'student2'), (12, 'student3'), (14, 'student4'), (48, 'student5'), (43, 'student6'), (47, 'student7'), (98, 'student8'), (35, 'student9'), (80, 'student10')]

    marks_to_students_zipped.sort(key=lambda item: item[0])
    # The "key" above specifies what criteria it should sort on
    # I am selecting [0] as it should be sorted on marks

    top_5_ranks_by_marks = least_5_ranks_by_marks = marks_to_students_zipped

    if len(marks_to_students_zipped) > 5:
        top_5_ranks_by_marks = marks_to_students_zipped[:-6: -1]
        # Above slice notation means -  the last 5 items, reversed
        least_5_ranks_by_marks = marks_to_students_zipped[:5]

    students_between_25_and_75_percentile = marks_to_students_zipped[math.ceil(0.25 * len(marks_to_students_zipped)):
                                                                     math.floor(0.75 * len(marks_to_students_zipped))]

    return top_5_ranks_by_marks, least_5_ranks_by_marks, students_between_25_and_75_percentile


Students = ['student1', 'student2', 'student3', 'student4', 'student5', 'student6', 'student7', 'student8', 'student9',
            'student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

display_dash_board(Marks, Students)


([(98, 'student8'),
  (80, 'student10'),
  (78, 'student2'),
  (48, 'student5'),
  (47, 'student7')],
 [(12, 'student3'),
  (14, 'student4'),
  (35, 'student9'),
  (43, 'student6'),
  (45, 'student1')],
 [(43, 'student6'), (45, 'student1'), (47, 'student7'), (48, 'student5')])

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math


def closest_points_to_p(S, P):
    total_list_of_closest_points_to_p = []
    result_closest_to_p = []

    for point in S:
        denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
        numerator = point[0] * P[0] + point[1] * P[1]

        if denominator != 0:
            cosine_distance_for_this_point = math.acos(numerator / denominator)
            total_list_of_closest_points_to_p.append((cosine_distance_for_this_point, point))

    # print('total_list_of_closest_points_to_p ', total_list_of_closest_points_to_p)
    # [(2.0344439357957027, (1, 2)), (1.8545904360032246, (3, 4)), (2.9996955989856287, (-1, 1)), (0.06512516333438509, (6, -7)), (2.498091544796509, (0, 6)), (1.2021004241368467, (-5, -8)), (1.4288992721907328, (-1, -1)), (0.9272952180016123, (6, 0)), (0.14189705460416438, (1, -1))]

    # So total_list_of_closest_points_to_p is an list of tuples and the first element
    # of each of the tuple is the actual 'cosine distance' . So I need to sort
    # total_list_of_closest_points_to_p by this first element

    for item in sorted(total_list_of_closest_points_to_p, key=lambda x: x[0])[:5]:
        # print('item is', item)
        # (0.06512516333438509, (6, -7))
        # (0.14189705460416438, (1, -1))
        # ...
        result_closest_to_p.append(item[1])

    return result_closest_to_p


S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P = (3, -4)

closest_points = closest_points_to_p(S, P)
print("5 Closest point to P based on cosine-distance:", *[point for point in closest_points], sep="\n")


5 Closest point to P based on cosine-distance:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math


def i_am_the_one(red, blue, line):
    sign_of_equation_with_red_point_tuple = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_of_equation_with_red_point_tuple = 1

    for red_point in red:
        if sign_of_equation_with_red_point_tuple == 1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) < 0:
            return 'NO'

        if sign_of_equation_with_red_point_tuple == -1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) > 0:
            return 'NO'

    # Now the same set of two traversal for the blue-points tuples

    sign_of_equation_with_blue_point_tuple = -1 * sign_of_equation_with_red_point_tuple

    for blue_point in blue:
        if sign_of_equation_with_blue_point_tuple == 1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) < 0:
            return 'NO'

        if sign_of_equation_with_blue_point_tuple == -1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) > 0:
            return 'NO'

    return 'YES'


Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]

Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
def curve_smoothing(string):
    index_of_non_empty_cells_list = []

    split_string = string.split(',')


    for idx in range(len(split_string)):
        if split_string[idx] != '_':
            index_of_non_empty_cells_list.append(idx)

    # Also add to index_of_non_empty_cells_list
    # The total index-length of the original list
    index_of_non_empty_cells_list.append(len(split_string) - 1)

    print(index_of_non_empty_cells_list)
    [2, 6, 8]

    # Now loop over index_of_non_empty_cells_list to modify the
    # original list by filing up empty_cells
    position_to_start = 0

    for element in index_of_non_empty_cells_list:
        # Wherever, there is a missing values, I have to add the immediately proceeding value
        # and the immediately next available value and then divide it by the number of missing values.
        # So, initiate a variable to 'cumulative_sum_prev_and_next_value' to hold the cumulative sum of
        # available (i.e. non-empty) cells
        cumulative_sum_prev_and_next_value = int(split_string[element]) if split_string[element] != '_' else 0
        cumulative_sum_prev_and_next_value += int(split_string[position_to_start]) if split_string[
                                                                                          position_to_start] != '_' and position_to_start != element else 0
        # print(cumulative_sum_prev_and_next_value)

        # Now divide the cumulative_sum of prev and next value
        # by the number of missing values
        integer_to_replace_each_previous_empty_cell = cumulative_sum_prev_and_next_value // (
                element - position_to_start + 1)

        # print("integer_to_replace_each_previous_empty_cell value is ", integer_to_replace_each_previous_empty_cell)
        # For the first loop it will give me 10 which is what I will replace each emtpy value with

        # And now modify the original list by replacing the empty cells with the above
        # value i.e.  integer_to_replace_each_previous_empty_cell
        split_string = [
            integer_to_replace_each_previous_empty_cell if position_to_start <= x <= element else split_string[x] for x
            in range(len(split_string))]

        # print("element: %s cumulative_sum_prev_and_next_value: %s  split_string: %s" %(element, cumulative_sum_prev_and_next_value, split_string ))

        # After original list has been updated by filling up the empty cells
        # now update the starting position for the next loop

        position_to_start = element

    return split_string

S = "_,_,30,_,_,_,50,_,_"
ans = smoothed_values = curve_smoothing(S)
# print(curve_smoothing(S))
print(ans)

[2, 6, 8]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
# https://stackoverflow.com/questions/57160252/find-conditional-probabilities-using-python
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

dictionary1 = {
 'F1S1':0,
 'F2S1':0,
 'F3S1':0,
 'F4S1':0,
 'F5S1':0,
 'F1S2':0,
 'F2S2':0,
 'F3S2':0,
 'F4S2':0,
 'F5S2':0,
 'F1S3':0,
 'F2S3':0,
 'F3S3':0,
 'F4S3':0,
 'F5S3':0,
}

dictionary2= {
 'S1':0,
 'S2':0,
 'S3':0
}

def compute_conditional_probabilites(A):
    for i in range(len(A)):
        if(A[i][0]=='F1'and A[i][1]=='S1'):
            dictionary1['F1S1'] = dictionary1['F1S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F1'and A[i][1]=='S2'):
            dictionary1['F1S2'] = dictionary1['F1S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F1'and A[i][1]=='S3'):
            dictionary1['F1S3'] = dictionary1['F1S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F2'and A[i][1]=='S1'):
            dictionary1['F2S1'] = dictionary1['F2S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F2'and A[i][1]=='S2'):
            dictionary1['F2S2'] = dictionary1['F2S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F2'and A[i][1]=='S3'):
            dictionary1['F2S3'] = dictionary1['F2S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F3'and A[i][1]=='S1'):
            dictionary1['F3S1'] = dictionary1['F3S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F3'and A[i][1]=='S2'):
            dictionary1['F3S2'] = dictionary1['F3S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F3'and A[i][1]=='S3'):
            dictionary1['F3S3'] = dictionary1['F3S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F4'and A[i][1]=='S1'):
            dictionary1['F4S1'] = dictionary1['F4S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F4'and A[i][1]=='S2'):
            dictionary1['F4S2'] = dictionary1['F4S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F4'and A[i][1]=='S3'):
            dictionary1['F4S3'] = dictionary1['F4S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F5'and A[i][1]=='S1'):
            dictionary1['F5S1'] = dictionary1['F5S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F5'and A[i][1]=='S2'):
            dictionary1['F5S2'] = dictionary1['F5S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F5'and A[i][1]=='S3'):
            dictionary1['F5S3'] = dictionary1['F5S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1                                

compute_conditional_probabilites(A)

print('Probability of P(F=F1|S==S1) =',(dictionary1['F1S1']/dictionary2['S1']))
print('Probability of P(F=F1|S==S2) =',(dictionary1['F1S2']/dictionary2['S2']))
print('Probability of P(F=F1|S==S3) =',(dictionary1['F1S3']/dictionary2['S3']))
print('Probability of P(F=F2|S==S1) =',(dictionary1['F2S1']/dictionary2['S1']))
print('Probability of P(F=F2|S==S2) =',(dictionary1['F2S2']/dictionary2['S2']))
print('Probability of P(F=F2|S==S3) =',(dictionary1['F2S3']/dictionary2['S3']))
print('Probability of P(F=F3|S==S1) =',(dictionary1['F3S1']/dictionary2['S1']))
print('Probability of P(F=F3|S==S2) =',(dictionary1['F3S2']/dictionary2['S2']))
print('Probability of P(F=F3|S==S3) =',(dictionary1['F3S3']/dictionary2['S3']))
print('Probability of P(F=F4|S==S1) =',(dictionary1['F4S1']/dictionary2['S1']))
print('Probability of P(F=F4|S==S2) =',(dictionary1['F4S2']/dictionary2['S2']))
print('Probability of P(F=F4|S==S3) =',(dictionary1['F4S3']/dictionary2['S3']))
print('Probability of P(F=F5|S==S1) =',(dictionary1['F5S1']/dictionary2['S1']))
print('Probability of P(F=F5|S==S2) =',(dictionary1['F5S2']/dictionary2['S2']))
print('Probability of P(F=F5|S==S3) =',(dictionary1['F5S3']/dictionary2['S3']))

Probability of P(F=F1|S==S1) = 0.25
Probability of P(F=F1|S==S2) = 0.3333333333333333
Probability of P(F=F1|S==S3) = 0.0
Probability of P(F=F2|S==S1) = 0.25
Probability of P(F=F2|S==S2) = 0.3333333333333333
Probability of P(F=F2|S==S3) = 0.3333333333333333
Probability of P(F=F3|S==S1) = 0.0
Probability of P(F=F3|S==S2) = 0.3333333333333333
Probability of P(F=F3|S==S3) = 0.3333333333333333
Probability of P(F=F4|S==S1) = 0.25
Probability of P(F=F4|S==S2) = 0.0
Probability of P(F=F4|S==S3) = 0.3333333333333333
Probability of P(F=F5|S==S1) = 0.25
Probability of P(F=F5|S==S2) = 0.0
Probability of P(F=F5|S==S3) = 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
def string_features(S1, S2):
    a=[]
    b=[]
    c=[]
    for ch in S1.split():
        for ch1 in S2.split():
            if(ch ==ch1):
                a.append(ch)
    print(len(a))
    b= list(set(S1.split())-set(S2.split()))
    print(b)
    c = list(set(S2.split())-set(S1.split()))
    print(c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
print(string_features(S1, S2))

7
['5', 'first', 'F']
['second', '3', 'S']
None


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
import math

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):
        sum = sum + ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    return sum 

print((compute_log_loss(A)/8)*(-1))

0.42430993457031635
